added dockerfile and yml

diff --git a/.github/workflows/unit-tests.yml b/.github/workflows/unit-tests.yml
--- a/.github/workflows/unit-tests.yml
+++ b/.github/workflows/unit-tests.yml
@@ -1,4 +1,4 @@
-name: Unit Tests with Report
+name: Tests with Report
 
 on:
   pull_request:
@@ -43,7 +43,7 @@ jobs:
         env:
           POSTGRES_USER: postgres
           POSTGRES_PASSWORD: postgres
-          POSTGRES_DB: testdb
+          POSTGRES_DB: integrationdb
         options: >-
           --health-cmd pg_isready
           --health-interval 10s
@@ -99,4 +99,73 @@ jobs:
       with:
         name: integration-test-report-on-failure
         path: test-results/integration-report.html
+        retention-days: 2
+        
+  e2e-tests:
+    runs-on: ubuntu-latest
+    needs: integration-tests  # Запускаем только после успешных integration-тестов
+    if: success()  # Только если предыдущий job успешен
+
+    services:
+      postgres:
+        image: postgres:15
+        env:
+          POSTGRES_USER: postgres
+          POSTGRES_PASSWORD: postgres
+          POSTGRES_DB: E2Edb
+        options: >-
+          --health-cmd pg_isready
+          --health-interval 10s
+          --health-timeout 5s
+          --health-retries 5
+        ports:
+          - 5432:5432
+
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v4
+
+    - name: Set up Docker Buildx
+      uses: docker/setup-buildx-action@v3
+
+    - name: Build E2E test image
+      run: docker build -t bd-E2E-tests -f Dockerfile.E2E .
+
+    - name: Wait for PostgreSQL to be ready
+      run: |
+        echo "Waiting for PostgreSQL to start..."
+        for i in {1..30}; do
+          if nc -z localhost 5432; then
+            echo "PostgreSQL is ready!"
+            exit 0
+          fi
+          echo "Waiting for PostgreSQL... Attempt $i/30"
+          sleep 2
+        done
+        echo "PostgreSQL failed to start within 60 seconds"
+        exit 1
+
+    - name: Run E2E tests with HTML output
+      run: |
+        mkdir -p test-results
+        docker run --rm \
+          --network host \
+          -e ConnectionStrings__TestDbConnection="Host=localhost;Port=5432;Database=testdb;Username=postgres;Password=postgres" \
+          -v $(pwd)/test-results:/test-results \
+          bd-E2E-tests \
+          --logger "html;LogFileName=/test-results/E2E-report.html"
+
+    - name: Upload E2E test results
+      uses: actions/upload-artifact@v4
+      with:
+        name: E2E-test-report
+        path: test-results/E2E-report.html
+        retention-days: 2
+
+    - name: Upload test results even on failure
+      if: always()
+      uses: actions/upload-artifact@v4
+      with:
+        name: E2E-test-report-on-failure
+        path: test-results/E2E-report.html
         retention-days: 2
